config/routes.rb
ScholarshipDemo::Application.routes.draw do
  resources :articles

  resources :scholarship_comments

  resources :suggestions

  resources :tags do
    resources :scholarships
  end

  resources :tag_contexts do
    resources :tags do
      resources :scholarships
    end
  end

  resources :scholarship_providers do
    resources :scholarships
  end
  
  resources :scholarships
  match 'scholarships/search/:query' => 'scholarships#search'
  match '/lists' => 'tag_contexts#list'

 root :to => "tag_contexts#index"

end

app/models/scholarship.rb
class Scholarship < ActiveRecord::Base
  belongs_to :provider, :class_name=>'ScholarshipProvider'
  has_and_belongs_to_many :tags
  has_many :comments, :class_name=>'ScholarshipComment'
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  respond_to :html, :xml, :json
  # GET /scholarships
  # GET /scholarships.xml
  def index
    # There's three ways to hit this page -- either all scholarships (no params), scholarships for a tag (tag_id),
    # or scholarships for a provider (scholarship_provider_id).  Probably a cleaner way to do this.
    @scholarships = params[:tag_id].nil? ? Scholarship.all : Tag.find(params[:tag_id]).scholarships
    if params[:scholarship_provider_id]
      @scholarships  = ScholarshipProvider.find(params[:scholarship_provider_id]).scholarships
    end
   respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scholarships }
      format.json  { render :json => @scholarships, :include=>:comments }
    end
  end

    def search
      # There's three ways to hit this page -- either all scholarships (no params), scholarships for a tag (tag_id),
      # or scholarships for a provider (scholarship_provider_id).  Probably a cleaner way to do this.
      @scholarships = Scholarship.where("name like ? or description like ?", "%#{params[:query]}%", "%#{params[:query]}%")
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @scholarships }
        format.json  { render :json => @scholarships, :include=>:comments }
      end
  #    respond_with @scholarships
    end

  # GET /scholarships/1
  # GET /scholarships/1.xml
  def show
    @scholarship = Scholarship.find(params[:id])

    respond_with @scholarship
  end

  # GET /scholarships/new
  # GET /scholarships/new.xml
  def new
    @scholarship = Scholarship.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scholarship }
    end
  end

  # GET /scholarships/1/edit
  def edit
    @scholarship = Scholarship.find(params[:id])
  end

  # POST /scholarships
  # POST /scholarships.xml
  def create
    @scholarship = Scholarship.new(params[:scholarship])

    respond_to do |format|
      if @scholarship.save
        format.html { redirect_to(@scholarship, :notice => 'Scholarship was successfully created.') }
        format.xml  { render :xml => @scholarship, :status => :created, :location => @scholarship }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @scholarship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scholarships/1
  # PUT /scholarships/1.xml
  def update
    @scholarship = Scholarship.find(params[:id])

    respond_to do |format|
      if @scholarship.update_attributes(params[:scholarship])
        format.html { redirect_to(@scholarship, :notice => 'Scholarship was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scholarship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarships/1
  # DELETE /scholarships/1.xml
  def destroy
    @scholarship = Scholarship.find(params[:id])
    @scholarship.destroy

    respond_to do |format|
      format.html { redirect_to(scholarships_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/views/scholarships/_form.html.haml
= semantic_form_for @scholarship do |f|
  = f.inputs do
    =f.input :provider, :required=>true
    =f.input :name, :required=>true
    =f.input :description, :required=>true
    =f.input :requirements
    =f.input :application_url, :required=>true
    
  =f.inputs do
    %h3  Deadline - Both are optional
    =f.input :deadline_date
    =f.input :deadline_comment
    
  =f.inputs do
    %h3 Which List?
    =f.input :tags, :as=>:select
    
  =f.inputs do
    =f.buttons

app/views/scholarships/_scholarship.html.haml
%tr
  %td
    =link_to scholarship.name, scholarship
  %td
    =scholarship.description

app/views/scholarships/edit.html.haml
- model_class = Scholarship
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/scholarships/index.html.haml
- model_class = Scholarship
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:provider)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:application_url)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @scholarships.each do |scholarship|
      %tr
        %td= scholarship.provider.name
        %td= link_to scholarship.name, edit_scholarship_path(scholarship), :title=>scholarship.description
        %td= scholarship.application_url
        %td
          = link_to t('.destroy', :default => t("helpers.links.destroy")), scholarship_path(scholarship), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_scholarship_path, :class => 'btn btn-primary'

app/views/scholarships/new.html.haml
- model_class = Scholarship
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/scholarships/show.html.haml
- model_class = Scholarship
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:provider_id) + ':'
  %br
  = link_to @scholarship.provider.name, @scholarship.provider
%p
  %strong Tags / Lists
  %ul
    - @scholarship.tags.each do |t|
      %li= "#{t.tag_context.label} : #{t.label}"
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @scholarship.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @scholarship.description
%p
  %strong= model_class.human_attribute_name(:requirements) + ':'
  %br
  = @scholarship.requirements
%p
  %strong= model_class.human_attribute_name(:award_size) + ':'
  %br
  = @scholarship.award_size
%p
  %strong= model_class.human_attribute_name(:deadline_date) + ':'
  %br
  = @scholarship.deadline_date
%p
  %strong= model_class.human_attribute_name(:deadline_comment) + ':'
  %br
  = @scholarship.deadline_comment
%p
  %strong= model_class.human_attribute_name(:application_url) + ':'
  %br
  = @scholarship.application_url
%p
  %strong= model_class.human_attribute_name(:renewable) + ':'
  %br
  = @scholarship.renewable
%p
  %strong= model_class.human_attribute_name(:number_of_awards) + ':'
  %br
  = @scholarship.number_of_awards
%p
  %strong= model_class.human_attribute_name(:one_time) + ':'
  %br
  = @scholarship.one_time
%p
  %strong= model_class.human_attribute_name(:award_min) + ':'
  %br
  = @scholarship.award_min
%p
  %strong= model_class.human_attribute_name(:award_max) + ':'
  %br
  = @scholarship.award_max

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), scholarships_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_scholarship_path(@scholarship), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), scholarship_path(@scholarship), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'