config/routes.rb
ScholarshipDemo::Application.routes.draw do
  resources :articles

  resources :scholarship_comments

  resources :suggestions

  resources :tags do
    resources :scholarships
  end

  resources :tag_contexts do
    resources :tags do
      resources :scholarships
    end
  end

  resources :scholarship_providers do
    resources :scholarships
  end
  
  resources :scholarships
  match 'scholarships/search/:query' => 'scholarships#search'
  match '/lists' => 'tag_contexts#list'

 root :to => "tag_contexts#index"

end

app/models/scholarship_provider.rb
class ScholarshipProvider < ActiveRecord::Base
  has_many :contacts, :class_name=>'ProviderContact'
  has_many :scholarships, :foreign_key=>'provider_id', :order=>"name"
  accepts_nested_attributes_for :scholarships, :reject_if=> proc {|attributes| attributes[:entry].blank?}, :allow_destroy => true

end

app/controllers/scholarship_providers_controller.rb
class ScholarshipProvidersController < ApplicationController
  respond_to :html, :json, :xml
  # GET /scholarship_providers
  # GET /scholarship_providers.xml
  def index
    @scholarship_providers = ScholarshipProvider.order("featured_position, name")
    respond_with @scholarship_providers, :include=>:scholarships
  end

  # GET /scholarship_providers/1
  # GET /scholarship_providers/1.xml
  def show
    @scholarship_provider = ScholarshipProvider.find(params[:id])
    respond_with @scholarship_provider, :include=>:scholarships
  end

  # GET /scholarship_providers/new
  # GET /scholarship_providers/new.xml
  def new
    @scholarship_provider = ScholarshipProvider.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scholarship_provider }
    end
  end

  # GET /scholarship_providers/1/edit
  def edit
    @scholarship_provider = ScholarshipProvider.find(params[:id])
  end

  # POST /scholarship_providers
  # POST /scholarship_providers.xml
  def create
    @scholarship_provider = ScholarshipProvider.new(params[:scholarship_provider])

    respond_to do |format|
      if @scholarship_provider.save
        format.html { redirect_to(@scholarship_provider, :notice => 'Scholarship provider was successfully created.') }
        format.xml  { render :xml => @scholarship_provider, :status => :created, :location => @scholarship_provider }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @scholarship_provider.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scholarship_providers/1
  # PUT /scholarship_providers/1.xml
  def update
    @scholarship_provider = ScholarshipProvider.find(params[:id])

    respond_to do |format|
      if @scholarship_provider.update_attributes(params[:scholarship_provider])
        format.json { respond_with_bip(@scholarship_provider) }
        format.html { redirect_to(@scholarship_provider, :notice => 'Scholarship provider was successfully updated.') }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scholarship_provider.errors, :status => :unprocessable_entity }
        format.json { respond_with_bip(@scholarship_provider) }
      end
    end
  end

  # DELETE /scholarship_providers/1
  # DELETE /scholarship_providers/1.xml
  def destroy
    @scholarship_provider = ScholarshipProvider.find(params[:id])
    @scholarship_provider.destroy

    respond_to do |format|
      format.html { redirect_to(scholarship_providers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/scholarship_providers_helper.rb
module ScholarshipProvidersHelper
end

app/views/scholarship_providers/_form.html.haml
= semantic_form_for @scholarship_provider do |f|
  = f.inputs do
    =f.input :name
    =f.input :description
    =f.input :url
    =f.input :featured_position
    
    #scholarships
      %h3 Scholarships
      = f.semantic_fields_for :scholarships do |scholarship|
        = render 'scholarship_fields', :f => scholarship
      .links
        = link_to_add_association 'add scholarship', f, :scholarships, :render_options => {:wrapper => 'inline' }
        
    =f.buttons
    

app/views/scholarship_providers/_scholarship_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :name
    = f.input :description
  = link_to_remove_association "remove scholarship", f

app/views/scholarship_providers/edit.html.haml
- model_class = ScholarshipProvider
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/scholarship_providers/index.html.haml
- model_class = ScholarshipProvider
.page-header
  %h1=t '.title', :default => "Scholarship Providers"
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:url)
      %th= model_class.human_attribute_name(:description)
      %th Number of Scholarships
      %th Featured Position
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @scholarship_providers.each do |scholarship_provider|
      %tr
        %td= link_to scholarship_provider.name, scholarship_provider
        %td= scholarship_provider.url
        %td= scholarship_provider.description
        %td= scholarship_provider.scholarships.count
        %td= scholarship_provider.featured_position
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_scholarship_provider_path(scholarship_provider), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), scholarship_provider_path(scholarship_provider), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_scholarship_provider_path, :class => 'btn btn-primary'

app/views/scholarship_providers/new.html.haml
- model_class = ScholarshipProvider
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/scholarship_providers/show.html.haml
- model_class = ScholarshipProvider
.page-header
  %h1=t '.title', :default => "Scholarship Provider"
  
%p
  %strong= model_class.human_attribute_name(:name) + ': '
  = best_in_place @scholarship_provider, :name, :nil=>"Click to edit name"

%p
  %strong= model_class.human_attribute_name(:description) + ': '
  = best_in_place @scholarship_provider, :description, :nil=>"Click to edit description"

%p
  %strong= model_class.human_attribute_name(:url) + ': '
  = best_in_place @scholarship_provider, :url, :nil=>"Click to edit URL"

%p
  %strong= model_class.human_attribute_name(:featured_position) + ': '
  = best_in_place @scholarship_provider, :featured_position, :nil=>"0"
  
%p
  %strong Scholarships
  %table
    =render @scholarship_provider.scholarships

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), scholarship_providers_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_scholarship_provider_path(@scholarship_provider), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), scholarship_provider_path(@scholarship_provider), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'