config/routes.rb
ScholarshipDemo::Application.routes.draw do
  resources :articles

  resources :scholarship_comments

  resources :suggestions

  resources :tags do
    resources :scholarships
  end

  resources :tag_contexts do
    resources :tags do
      resources :scholarships
    end
  end

  resources :scholarship_providers do
    resources :scholarships
  end
  
  resources :scholarships
  match 'scholarships/search/:query' => 'scholarships#search'
  match '/lists' => 'tag_contexts#list'

 root :to => "tag_contexts#index"

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :tag_context
  has_and_belongs_to_many :scholarships, :order=>"name"
  has_permalink :label
  
  def to_s
    self.label
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  respond_to :html, :xml, :json
  # GET /tags
  # GET /tags.xml
  def index
    @tags = params[:tag_context_id].nil? ? Tag.all : Tag.where(:tag_context_id=>params[:tag_context_id])
    respond_with @tags
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find_by_permalink(params[:id])
    respond_with @tag, :include=>:scholarships
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find_by_permalink(params[:id])
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to(@tag, :notice => 'Tag was successfully created.') }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find_by_permalink(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.find_by_permalink(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= semantic_form_for @tag do |f|
  = f.inputs do
    =f.input :label, :required=>true
    = f.input :teaser, :input_html => { :size => 80 }
    = f.input :writeup, :input_html => { :class => 'autogrow', :rows => 5, :cols => 40  }
    = f.input :icon, :required=>true
    =f.input :tag_context, :required=>true
    =f.buttons

app/views/tags/edit.html.haml
- model_class = Tag
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/tags/index.html.haml
- model_class = Tag
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:label)
      %th Teaser
      %th Scholarships
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @tags.each do |tag|
      %tr
        %td= link_to tag.id, tag_path(tag)
        %td= tag.label
        %td= tag.teaser
        %td= tag.scholarships.size
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_tag_path(tag), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), tag_path(tag), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_tag_path, :class => 'btn btn-primary'

app/views/tags/new.html.haml
- model_class = Tag
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/tags/show.html.haml
- model_class = Tag
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:label) + ':'
  %br
  = @tag.label
%p
  %strong= model_class.human_attribute_name(:tag_context_id) + ':'
  %br
  = link_to @tag.tag_context.label, @tag.tag_context

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), tags_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_tag_path(@tag), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), tag_path(@tag), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'