config/routes.rb
ScholarshipDemo::Application.routes.draw do
  resources :articles

  resources :scholarship_comments

  resources :suggestions

  resources :tags do
    resources :scholarships
  end

  resources :tag_contexts do
    resources :tags do
      resources :scholarships
    end
  end

  resources :scholarship_providers do
    resources :scholarships
  end
  
  resources :scholarships
  match 'scholarships/search/:query' => 'scholarships#search'
  match '/lists' => 'tag_contexts#list'

 root :to => "tag_contexts#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scholarship Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :cocoon %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Scholarships Manager</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Providers(#{ScholarshipProvider.count})", scholarship_providers_path %></li>
            <li><%= link_to "Scholarships(#{Scholarship.count})", scholarships_path %></li>
            <li><%= link_to "Comments(#{ScholarshipComment.count})", scholarship_comments_path %></li>
            <li><%= link_to "Lists(#{TagContext.count})", tag_contexts_path %></li>
            <li><%= link_to "Tags(#{Tag.count})", tags_path %></li>
            <li><%= link_to "Suggestions(#{Suggestion.count})", suggestions_path %></li>
            <li><%= link_to "Articles(#{Article.count})", articles_path %></li>
            
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
    </div>
</body>
</html>

app/views/layouts/new_suggestion.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scholarship Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :cocoon %>
  
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/scholarships_table.html.haml
This is the header
=yield
This is the footer